# Generated by Django 2.0.7 on 2018-07-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='type',
            field=models.CharField(default='explicit', max_length=8),
        ),
    ]
